[project]
name = "equivariant-rl"
version = "0.1.0"
description = ""
authors = [
    {name = "Your Name",email = "you@example.com"}
]
readme = "README.md"
requires-python = ">=3.11, <3.12"
packages = [
  { include = "so2_equiv_rl" },
]
dependencies = [
    "numpy (>=2.0,<3.0.0)",
    "torch (>=2.9.0,<3.0.0)",
    "gymnasium (>=1.2.2,<2.0.0)",
    "ale-py (>=0.11.2,<0.12.0)",
    "tyro (>=0.9.35,<0.10.0)",
    "tensorboard (>=2.20.0,<3.0.0)",
    "autorom (>=0.6.1,<0.7.0)",
    "opencv-python (>=4.12.0.88,<5.0.0.0)",
    "scipy (>=1.16.3,<2.0.0)",
    "joblib (>=1.5.2,<2.0.0)"
]

[[tool.poetry.packages]]
include = "so2_equiv_rl"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
